name = "ssl-dropship"
compatibility_date = "2024-03-26"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm install --legacy-peer-deps && npm run build" 