// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzoerrcjxcafmbundltd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6b2VycmNqeGNhZm1idW5kbHRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDQxOTAsImV4cCI6MjA1Nzg4MDE5MH0.V7LMD1psvdJRnPq-p7a_rhx8EUuJMoUqdVHQPeExMvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);